/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.main;

import constant.Flag;
import app_learn_english.Frame;
import constant.parameters;
/**
 *
 * @author Computer's Tien
 */
public class ChoseLevel extends javax.swing.JPanel {
    private Frame jf;
    private final ChoseLesson choseLesson;
    
    
    //khai báo các lesson của các level
    /**
     * Creates new form ChoseLesson
     * @param jf
     */
    public ChoseLevel(Frame jf,ChoseLesson choseLesson) {       
        this.jf = jf;
        initComponents();
        this.choseLesson = choseLesson;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mediumButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        easyButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 500));

        jLabel2.setBackground(new java.awt.Color(255, 239, 23));
        jLabel2.setFont(new java.awt.Font("Snap ITC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chose Level");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mediumButton.setBackground(new java.awt.Color(255, 153, 153));
        mediumButton.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        mediumButton.setForeground(new java.awt.Color(51, 51, 255));
        mediumButton.setText("MEDIUM");
        mediumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mediumButtonMouseReleased(evt);
            }
        });

        hardButton.setBackground(new java.awt.Color(255, 255, 204));
        hardButton.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        hardButton.setForeground(new java.awt.Color(51, 255, 51));
        hardButton.setText("HARD");
        hardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hardButtonMouseReleased(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        backButton.setForeground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backicon.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });

        easyButton1.setBackground(new java.awt.Color(255, 153, 204));
        easyButton1.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        easyButton1.setForeground(new java.awt.Color(0, 255, 204));
        easyButton1.setText("EASY");
        easyButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                easyButton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mediumButton, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(easyButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(easyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mediumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(hardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
        jf.home();
    }//GEN-LAST:event_backButtonMouseReleased

    private void mediumButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumButtonMouseReleased
        Flag.setLevel(parameters.flagMediumLevel);
        choseLesson.setupLesson();
        jf.choseLesson();
    }//GEN-LAST:event_mediumButtonMouseReleased

    private void hardButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardButtonMouseReleased
        Flag.setLevel(parameters.flagHardLevel);
        choseLesson.setupLesson();
        jf.choseLesson();
    }//GEN-LAST:event_hardButtonMouseReleased

    private void easyButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyButton1MouseReleased
        Flag.setLevel(parameters.flagEasyLevel);
        choseLesson.setupLesson();
        jf.choseLesson();
    }//GEN-LAST:event_easyButton1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton easyButton1;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mediumButton;
    // End of variables declaration//GEN-END:variables
}
