/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.main;

import constant.Flag;
import app_learn_english.Frame;
import constant.parameters;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import connectdatabase.QueryDatabase;
/**
 *
 * 
 * @author Computer's Tien
 */
public class ChoseLesson extends JPanel{
    private Frame jf;  
  
    /**
     * Creates new form Easy
     * @param jf
     */
    public ChoseLesson(Frame jf){
        this.jf = jf;   
        //khởi tạo tất cả các lesson
        initComponents();
        
    }
      
    private int checkFlagLevel(){
        return Flag.getLevel();
    }
    
   
    public void setupLesson(){
        int temp = 0;
        switch (checkFlagLevel()){
            case parameters.flagEasyLevel:
        
            try {
                //easyLessons = hàm khởi tạo query từ database
                ResultSet rs =  QueryDatabase.select("*", "lesson", "level_id = " + parameters.flagEasyLevel);
                // chỗ này query các thông tin ra rồi gắn vào là xong.
                int i=0;                
                while(rs.next()){
                    JPanel p = (JPanel)panelLessons.getComponent(i);
                    JPanel infor = (JPanel)p.getComponent(temp);
                    JLabel id = (JLabel)p.getComponent(2);
                    id.setText("Lesson" + (rs.getInt("lesson_id")));
                    setInforLesson(infor, rs.getString("topic"),rs.getString("all_time"),"nothing :D");
                    i++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChoseLesson.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ChoseLesson.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
                break;
            case parameters.flagMediumLevel:
            
                //easyLessons = hàm khởi tạo query từ database
                try {
                //easyLessons = hàm khởi tạo query từ database
                ResultSet rs =  QueryDatabase.select("*", "lesson", "level_id = " + parameters.flagMediumLevel);
                // chỗ này query các thông tin ra rồi gắn vào là xong.
                int i=0;               
                while(rs.next()){
                    JPanel p = (JPanel)panelLessons.getComponent(i);
                    JPanel infor = (JPanel)p.getComponent(temp);
                    JLabel id = (JLabel)p.getComponent(2);
                    id.setText("Lesson" + (rs.getInt("lesson_id")-4));
                    setInforLesson(infor, rs.getString("topic"),rs.getString("all_time"),"nothing :D");
                    
                    i++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChoseLesson.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ChoseLesson.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
            case parameters.flagHardLevel:
                //easyLessons = hàm khởi tạo query từ database
                try {
                //easyLessons = hàm khởi tạo query từ database
                ResultSet rs =  QueryDatabase.select("*", "lesson", "level_id = " + parameters.flagHardLevel);
                // chỗ này query các thông tin ra rồi gắn vào là xong.
                int i=0;
                
                while(rs.next()){
                    JPanel p = (JPanel)panelLessons.getComponent(i);
                    JPanel infor = (JPanel)p.getComponent(temp);
                    JLabel id = (JLabel)p.getComponent(2);
                    id.setText("Lesson" + (rs.getInt("lesson_id")-8));
                    setInforLesson(infor, rs.getString("topic"),rs.getString("all_time"),"nothing :D");
                    i++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChoseLesson.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ChoseLesson.class.getName()).log(Level.SEVERE, null, ex);
            }
               break;              
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        panelLessons = new javax.swing.JPanel();
        panelLesson1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buttonLesson1 = new javax.swing.JButton();
        inforLesson1 = new javax.swing.JPanel();
        nameLesson1 = new javax.swing.JLabel();
        timeLesson1 = new javax.swing.JLabel();
        senLesson1 = new javax.swing.JLabel();
        panelLesson2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        buttonLesson2 = new javax.swing.JButton();
        inforLesson2 = new javax.swing.JPanel();
        nameLesson2 = new javax.swing.JLabel();
        timeLesson2 = new javax.swing.JLabel();
        senLesson2 = new javax.swing.JLabel();
        panelLesson3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buttonLesson3 = new javax.swing.JButton();
        inforLesson3 = new javax.swing.JPanel();
        nameLesson3 = new javax.swing.JLabel();
        timeLesson3 = new javax.swing.JLabel();
        senLesson3 = new javax.swing.JLabel();
        panelLesson4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        buttonLesson4 = new javax.swing.JButton();
        inforLesson4 = new javax.swing.JPanel();
        nameLesson4 = new javax.swing.JLabel();
        timeLesson4 = new javax.swing.JLabel();
        senLesson4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 550));

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setForeground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backicon.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.setMaximumSize(new java.awt.Dimension(53, 52));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });

        panelLessons.setPreferredSize(new java.awt.Dimension(550, 400));
        panelLessons.setLayout(new java.awt.GridLayout(2, 0));

        panelLesson1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        panelLesson1.setName(""); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LESSON1");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));

        buttonLesson1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playicon.png"))); // NOI18N
        buttonLesson1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonLesson1.setPreferredSize(new java.awt.Dimension(40, 46));
        buttonLesson1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonLesson1MousePressed(evt);
            }
        });

        inforLesson1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inforLesson1.setName(""); // NOI18N

        nameLesson1.setBackground(new java.awt.Color(204, 0, 51));
        nameLesson1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nameLesson1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLesson1.setText("j");
        nameLesson1.setBorder(new javax.swing.border.MatteBorder(null));
        nameLesson1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameLesson1.setMaximumSize(new java.awt.Dimension(34, 34));

        timeLesson1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        timeLesson1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLesson1.setText("jLabel2");
        timeLesson1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        senLesson1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        senLesson1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senLesson1.setText("jLabel3");
        senLesson1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout inforLesson1Layout = new javax.swing.GroupLayout(inforLesson1);
        inforLesson1.setLayout(inforLesson1Layout);
        inforLesson1Layout.setHorizontalGroup(
            inforLesson1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLesson1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(senLesson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLesson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLesson1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );
        inforLesson1Layout.setVerticalGroup(
            inforLesson1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLesson1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(nameLesson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(timeLesson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(senLesson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout panelLesson1Layout = new javax.swing.GroupLayout(panelLesson1);
        panelLesson1.setLayout(panelLesson1Layout);
        panelLesson1Layout.setHorizontalGroup(
            panelLesson1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLesson1Layout.createSequentialGroup()
                .addComponent(inforLesson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLesson1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLesson1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonLesson1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelLesson1Layout.setVerticalGroup(
            panelLesson1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelLesson1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLesson1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inforLesson1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        inforLesson1.getAccessibleContext().setAccessibleDescription("");

        panelLessons.add(panelLesson1);

        panelLesson2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LESSON2");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));

        buttonLesson2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playicon.png"))); // NOI18N
        buttonLesson2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonLesson2.setPreferredSize(new java.awt.Dimension(40, 46));
        buttonLesson2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonLesson2MousePressed(evt);
            }
        });

        nameLesson2.setBackground(new java.awt.Color(204, 0, 51));
        nameLesson2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nameLesson2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLesson2.setText("j");
        nameLesson2.setBorder(new javax.swing.border.MatteBorder(null));
        nameLesson2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameLesson2.setMaximumSize(new java.awt.Dimension(34, 34));

        timeLesson2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        timeLesson2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLesson2.setText("jLabel2");
        timeLesson2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        senLesson2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        senLesson2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senLesson2.setText("jLabel3");
        senLesson2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout inforLesson2Layout = new javax.swing.GroupLayout(inforLesson2);
        inforLesson2.setLayout(inforLesson2Layout);
        inforLesson2Layout.setHorizontalGroup(
            inforLesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(senLesson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLesson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLesson2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );
        inforLesson2Layout.setVerticalGroup(
            inforLesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLesson2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(nameLesson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(timeLesson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(senLesson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout panelLesson2Layout = new javax.swing.GroupLayout(panelLesson2);
        panelLesson2.setLayout(panelLesson2Layout);
        panelLesson2Layout.setHorizontalGroup(
            panelLesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLesson2Layout.createSequentialGroup()
                .addComponent(inforLesson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLesson2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonLesson2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelLesson2Layout.setVerticalGroup(
            panelLesson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLesson2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLesson2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inforLesson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelLessons.add(panelLesson2);

        panelLesson3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 153)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LESSON3");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));

        buttonLesson3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playicon.png"))); // NOI18N
        buttonLesson3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonLesson3.setPreferredSize(new java.awt.Dimension(40, 46));
        buttonLesson3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonLesson3MousePressed(evt);
            }
        });

        nameLesson3.setBackground(new java.awt.Color(204, 0, 51));
        nameLesson3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nameLesson3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLesson3.setText("j");
        nameLesson3.setBorder(new javax.swing.border.MatteBorder(null));
        nameLesson3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameLesson3.setMaximumSize(new java.awt.Dimension(34, 34));

        timeLesson3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        timeLesson3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLesson3.setText("jLabel2");
        timeLesson3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        senLesson3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        senLesson3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senLesson3.setText("jLabel3");
        senLesson3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout inforLesson3Layout = new javax.swing.GroupLayout(inforLesson3);
        inforLesson3.setLayout(inforLesson3Layout);
        inforLesson3Layout.setHorizontalGroup(
            inforLesson3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLesson3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(senLesson3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLesson3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLesson3, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );
        inforLesson3Layout.setVerticalGroup(
            inforLesson3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLesson3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(nameLesson3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(timeLesson3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(senLesson3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout panelLesson3Layout = new javax.swing.GroupLayout(panelLesson3);
        panelLesson3.setLayout(panelLesson3Layout);
        panelLesson3Layout.setHorizontalGroup(
            panelLesson3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLesson3Layout.createSequentialGroup()
                .addComponent(inforLesson3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLesson3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLesson3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonLesson3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelLesson3Layout.setVerticalGroup(
            panelLesson3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLesson3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLesson3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inforLesson3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelLessons.add(panelLesson3);

        panelLesson4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 204)));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LESSON4");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));

        buttonLesson4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playicon.png"))); // NOI18N
        buttonLesson4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonLesson4.setPreferredSize(new java.awt.Dimension(40, 46));
        buttonLesson4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonLesson4MousePressed(evt);
            }
        });

        nameLesson4.setBackground(new java.awt.Color(204, 0, 51));
        nameLesson4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nameLesson4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLesson4.setText("j");
        nameLesson4.setBorder(new javax.swing.border.MatteBorder(null));
        nameLesson4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameLesson4.setMaximumSize(new java.awt.Dimension(34, 34));

        timeLesson4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        timeLesson4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLesson4.setText("jLabel2");
        timeLesson4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        senLesson4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        senLesson4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senLesson4.setText("jLabel3");
        senLesson4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout inforLesson4Layout = new javax.swing.GroupLayout(inforLesson4);
        inforLesson4.setLayout(inforLesson4Layout);
        inforLesson4Layout.setHorizontalGroup(
            inforLesson4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLesson4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(senLesson4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLesson4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLesson4, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );
        inforLesson4Layout.setVerticalGroup(
            inforLesson4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforLesson4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(nameLesson4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(timeLesson4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(senLesson4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout panelLesson4Layout = new javax.swing.GroupLayout(panelLesson4);
        panelLesson4.setLayout(panelLesson4Layout);
        panelLesson4Layout.setHorizontalGroup(
            panelLesson4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLesson4Layout.createSequentialGroup()
                .addComponent(inforLesson4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLesson4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLesson4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonLesson4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelLesson4Layout.setVerticalGroup(
            panelLesson4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLesson4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLesson4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inforLesson4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelLessons.add(panelLesson4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLessons, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLessons, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
        //hủy bỏ đối tượng
//        if(easyLessons != null)
//        for(int i=0;i<easyLessons.length;i++)
//            if(easyLessons[i] != null) easyLessons[i] = null;
//        if(mediumLessons != null)
//        for(int i=0;i<mediumLessons.length;i++)
//            if(mediumLessons[i] != null) mediumLessons[i] = null;
//        if(hardLessons != null)
//        for(int i=0;i<hardLessons.length;i++)
//            if(hardLessons[i] != null) hardLessons[i] = null;
        
        jf.choseLevel();
    }//GEN-LAST:event_backButtonMouseReleased

    private void buttonLesson1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLesson1MousePressed
        // TODO add your handling code here:
        // nạp 1 list các phần nghe sau đó gửi về client playlesson
        
        Flag.setLesson(1);
        jf.play();
    }//GEN-LAST:event_buttonLesson1MousePressed

    private void buttonLesson2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLesson2MousePressed
        // TODO add your handling code here:
        Flag.setLesson(2);
        jf.play();
    }//GEN-LAST:event_buttonLesson2MousePressed

    private void buttonLesson3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLesson3MousePressed
        // TODO add your handling code here:
        Flag.setLesson(3);
        jf.play();
    }//GEN-LAST:event_buttonLesson3MousePressed

    private void buttonLesson4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLesson4MousePressed
        // TODO add your handling code here:
        Flag.setLesson(4);
        jf.play();
    }//GEN-LAST:event_buttonLesson4MousePressed
    private void setInforLesson(JPanel inforLesson,String nameLesson, String timeLesson, String firstSentence){
        //System.out.println(this.panelLesson1.getComponentCount());
        //component chạy từ 1.
            
            JLabel name = (JLabel)inforLesson.getComponent(1);
            name.setText("name: " + nameLesson); //"name" + Lesson.getName()
            JLabel time = (JLabel)inforLesson.getComponent(2);
            time.setText("time: " + timeLesson  + " senconds");
            JLabel startSentence = (JLabel)inforLesson.getComponent(0);
            startSentence.setText("recommend: " + firstSentence);
    }
    
    //setaction cho các button khi nhấn button thì trả về 1 list các bài hát
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonLesson1;
    private javax.swing.JButton buttonLesson2;
    private javax.swing.JButton buttonLesson3;
    private javax.swing.JButton buttonLesson4;
    private javax.swing.JPanel inforLesson1;
    private javax.swing.JPanel inforLesson2;
    private javax.swing.JPanel inforLesson3;
    private javax.swing.JPanel inforLesson4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nameLesson1;
    private javax.swing.JLabel nameLesson2;
    private javax.swing.JLabel nameLesson3;
    private javax.swing.JLabel nameLesson4;
    private javax.swing.JPanel panelLesson1;
    private javax.swing.JPanel panelLesson2;
    private javax.swing.JPanel panelLesson3;
    private javax.swing.JPanel panelLesson4;
    private javax.swing.JPanel panelLessons;
    private javax.swing.JLabel senLesson1;
    private javax.swing.JLabel senLesson2;
    private javax.swing.JLabel senLesson3;
    private javax.swing.JLabel senLesson4;
    private javax.swing.JLabel timeLesson1;
    private javax.swing.JLabel timeLesson2;
    private javax.swing.JLabel timeLesson3;
    private javax.swing.JLabel timeLesson4;
    // End of variables declaration//GEN-END:variables
}
