/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.main;

import app_learn_english.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import connectdatabase.QueryDatabase;

/**
 *
 * @author Computer's Tien
 */
public class History extends javax.swing.JPanel {
    private Frame jf;
    /**
     * Creates new form History
     */
    public History(Frame jf) {
        this.jf = jf;
        initComponents();
        textArea.setText("");
    }
    
    public void queryHistory(){
        try {
            String what = "level_id,lesson_id,topic,score,created_at";
            String table = "history" + " order by created_at desc";
            
            ResultSet rs = QueryDatabase.select(what,table);
            textArea.setText("    Your history \n");
            textArea.append("    level_id     lesson_id       topic          score              created at   \n");
            while(rs.next()){
                textArea.append("    " + rs.getInt("level_id") + "                " + rs.getInt("lesson_id") + "                       " +
                        rs.getString("topic") + "          " + rs.getDouble("score")
                        + "            " + rs.getDate("created_at")+"__"+rs.getTime("created_at") + "\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        show = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(550, 500));

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setForeground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backicon.png"))); // NOI18N
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.setMaximumSize(new java.awt.Dimension(53, 52));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(255, 153, 153));

        textArea.setBackground(new java.awt.Color(204, 204, 204));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textArea.setForeground(new java.awt.Color(153, 0, 0));
        textArea.setRows(5);
        textArea.setAutoscrolls(false);
        textArea.setBorder(new javax.swing.border.MatteBorder(null));
        textArea.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textArea.setEnabled(false);
        jScrollPane1.setViewportView(textArea);

        show.setBackground(new java.awt.Color(102, 255, 51));
        show.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(255, 102, 102));
        show.setText("SHOW");
        show.setToolTipText("SHOW HISTORY");
        show.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
        textArea.setText("");
        show.setText("SHOW");
        jf.home();
    }//GEN-LAST:event_backButtonMouseReleased

    private void showMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseReleased
        // TODO add your handling code here:
        if(textArea.getText().equals("")){
            queryHistory();
            show.setText("HIDDEN");
        }
        else{
            textArea.setText("");
            show.setText("SHOW");
        }
    }//GEN-LAST:event_showMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton show;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
